--- 
title: "A Primer on Bayesian Optimization"
author: "Kumaraguru Sivasankaran"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a review on current advances in Bayesian optimization and a working book that will be updated time-to-time"
---

# Prerequisites

I think anyone with introductory Grad-level courses in Machine learning, Optimization, Statistics should be able to appreciate and enjoy this book. This is intended especially for someone looking to use Bayesian optimization/ starting research on Bayesian optimization.

```{r eval=FALSE, include=FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
```


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
